# Generated by Django 5.1 on 2024-10-25 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
